### ISSUE TITLE
Todo list for GameEngine

### ISSUE THREAD

**Issue by boranyldrm** [boranyldrm/CS319-2c#9]
- [ ] Main Character movement(right, mid, left) according to key controls.

- [ ] move the obstacles from top to down. [move obstacles from this loop](https://github.com/boranyldrm/CS319-2c/blob/master/DribbleandScore/src/game/GameEngine.java#L103)

- [ ] check for collision of main character to any obstacle, mud or bonus

- [ ] [1 second while loop](https://github.com/boranyldrm/CS319-2c/blob/master/DribbleandScore/src/game/GameEngine.java#L94) move the obstacles and resume the game, then new obstacles are generated.

- [ ] **_(may be ignored)_** run the GUI from [GameEngineRun](https://github.com/boranyldrm/CS319-2c/blob/master/DribbleandScore/src/game/GameEngineRun.java)
- [ ] clean unused variables.
